#!/bin/sh  

# This is the example configuration file for river. 
# 
# If you wish to edit this, you will probably want to copy it to 
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first. 
# 
# See the river(1), riverctl(1), and rivertile(1) man pages for complete 
# documentation.  
# Use the "logo" key as the primary modifier 
mod="Mod4"

# Mod+Shift+Return to start an instance of alacritty (https://codeberg.org/dnkl/foot) 
riverctl map normal $mod Return spawn alacritty
# Mod+Ctrl+E to open a emacsclient frame
riverctl map normal $mod+Control E spawn 'emacsclient -c'

# Mod+P to open wofi (rofi replacement)
riverctl map normal $mod P spawn 'wofi --show drun -I -G -L 5'
# Mod+Q to close the focused view 
riverctl map normal $mod Q close

# Mod+Shift+E to exit river 
riverctl map normal $mod+Shift Q exit

# Mod+J and Mod+K to focus the next/previous view in the layout stack 
riverctl map normal $mod J focus-view next 
riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod W focus-output next
riverctl map normal $mod E focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift W send-to-output next
riverctl map normal $mod+Shift E send-to-output previous

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod+Shift Return zoom

# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# Mod+Alt+{H,J,K,L} to move views
riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100 
riverctl map normal $mod+Mod1 K move up 100 
riverctl map normal $mod+Mod1 L move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges 
riverctl map normal $mod+Mod1+Control H snap left 
riverctl map normal $mod+Mod1+Control J snap down 
riverctl map normal $mod+Mod1+Control K snap up 
riverctl map normal $mod+Mod1+Control L snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal $mod+Mod1+Shift H resize horizontal -100 
riverctl map normal $mod+Mod1+Shift J resize vertical 100 
riverctl map normal $mod+Mod1+Shift K resize vertical -100 
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

# Mod + Left Mouse Button to move views 
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views 
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))     
    # Mod+[1-9] to focus tag [0-8]     
    riverctl map normal $mod $i set-focused-tags $tags     
    # Mod+Shift+[1-9] to tag focused view with tag [0-8]     
    riverctl map normal $mod+Shift $i set-view-tags $tags     
    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]     
    riverctl map normal $mod+Control $i toggle-focused-tags $tags     
    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view     
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1)) 
riverctl map normal $mod 0 set-focused-tags $all_tags 
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Mod+Space to toggle float 
riverctl map normal $mod Space toggle-float

# Mod+F to toggle fullscreen 
riverctl map normal $mod F toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change layout orientation 
riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top" 
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right" 
riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom" 
riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor 
riverctl declare-mode passthrough

# Mod+F11 to enter passthrough mode 
riverctl map normal $mod F11 enter-mode passthrough

# Mod+F11 to return to normal mode 
riverctl map passthrough $mod F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier for mode in normal locked do not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)     
    riverctl map $mode None XF86AudioRaiseVolume  spawn "IncreaseVolume.sh"     
    riverctl map $mode None XF86AudioLowerVolume  spawn "LowerVolume.sh"     
    riverctl map $mode None XF86AudioMute         spawn "ToggleVolume.sh"
    # Control screen backlight brighness with light (https://github.com/haikarainen/light)  
    riverctl map $mode None XF86MonBrightnessUp   spawn  "IncreaseLuce.sh"     
    riverctl map $mode None XF86MonBrightnessDown spawn  "LowerLuce.sh"
    riverctl map $mode None XF86AudioPlay         spawn  "mpc toggle"
done

# Set background and border color 
riverctl background-color 0x002b36 
riverctl border-color-focused 0x93a1a1 
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate 
riverctl set-repeat 50 300

# Make certain views start floating 
riverctl float-filter-add app-id float 
riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations 
riverctl csd-filter-add app-id "gedit"

# inputs configuration
riverctl input 2:7:SynPS/2_Synaptics_TouchPad events enabled
riverctl input 2:7:SynPS/2_Synaptics_TouchPad tap-button-map left-right-middle
riverctl input 2:7:SynPS/2_Synaptics_TouchPad tap enabled
riverctl input 2:7:SynPS/2_Synaptics_TouchPad scroll-method two-finger
riverctl input 2:7:SynPS/2_Synaptics_TouchPad natural-scroll enabled

# autostart
~/.config/river/autostart.sh &

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit. 
riverctl default-layout rivertile
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec rivertile -view-padding 3 -outer-padding 6
